### ISSUE TITLE
committeeMemberC needed in BSUthesis.sty

### ISSUE THREAD

**Issue by ajakef** [dylanmikesell/BSU_LaTeX_Thesis_Template#10]
The following code should be added to BSUthesis.sty (after the corresponding committeeMemberB sections):

% committee member C
\def\committeeMemberC{\@ifnextchar[{\@committeeMemberC}{\@committeeMemberC[Member, Supervisory Committee]}}
\def\@committeeMemberC[#1]#2#3{\gdef\@committeeMemberCname{#2}\gdef\@committeeMemberCtitle{#3}
\gdef\@committeeMemberCfunction{#1}}

and 

{\@committeeMemberCname} {\@committeeMemberCtitle} \hspace{2cm} & {\@committeeMemberCfunction}

Maybe add some committeeMemberD code too for good measure.

**Comment by dylanmikesell** [comment]
Fixed with 3b3d0ed. Would probably be useful to have IF to catch if committee member C is defined or not.
