### ISSUE TITLE
\degree command definition in BSUthesis.sty conflicts with gensymb package

### ISSUE THREAD

**Issue by ajakef** [dylanmikesell/BSU_LaTeX_Thesis_Template#11]
The \degree command in BSUthesis.sty conflicts with the \degree command in the common package gensymb (to make the degree symbol). This issue can be resolved by renaming the \degree command in BSUthesis.sty and BSUmain.tex:

BSUthesis.sty: \def\degreetype#1{\gdef\@degree{#1}}
BSUmain.tex: \degreetype{Doctor of Philosophy}

instead of 
BSUthesis.sty: \def\degree#1{\gdef\@degree{#1}} % conflicts with gensymb
BSUmain.tex: \degree{Doctor of Philosophy}

**Comment by dylanmikesell** [comment]
What Tex are you running? I just tested with  pdfTeX, Version 3.14159265-2.6-1.40.19 (TeX Live 2018) and I see nothing about this conflict.

**Comment by ajakef** [comment]
I'm running 3.14159265-2.6-1.40.16 .

When I change BSUmain.tex and BSUthesis.sty back to using \degree instead
of my renamed \graduatedegree, here's what the first couple pages of the
output look like. The first page is just the degree symbol and degree name,
and the title page is the second page, with no degree name.

[image: image.png]
[image: image.png]

**Comment by dylanmikesell** [comment]
Fixed with 76eb3b1.
