### ISSUE TITLE
Update link to location of CS latex style files

### ISSUE THREAD

**Issue by boiseamit** [dylanmikesell/BSU_LaTeX_Thesis_Template#12]
Please update the link in the following line in the README.md file to point to https://github.com/BoiseState/thesis-dissertation-template

If you are a Computer Science major, you can find the CS Master's thesis template from Amit Jain [here](http://cs.boisestate.edu/~amit/teaching/handouts/CS%20MS%20Thesis%20Style.html).

**Comment by dylanmikesell** [comment]
Fixed in commit [06c0ad3](https://github.com/dylanmikesell/BSU_LaTeX_Thesis_Template/commit/06c0ad375e2cd64c00ab3604f0c03cc011dd4c10).
