### ISSUE TITLE
Replace signature page with Final reading approval page

### ISSUE THREAD

**Issue by RebekahFLee** [dylanmikesell/BSU_LaTeX_Thesis_Template#2]
This is a template of the file that should go in place of the final reading approval page

[Ethesis_ Lee.Approval-Page (17).pdf](https://github.com/dylanmikesell/BSU_LaTeX_Thesis_Template/files/1468438/Ethesis_.Lee.Approval-Page.17.pdf)

**Comment by dylanmikesell** [comment]
Fixed with commit 3591f8e.
