### ISSUE TITLE
Margins and Page Numbers

### ISSUE THREAD

**Issue by RebekahFLee** [dylanmikesell/BSU_LaTeX_Thesis_Template#3]
Currently the margins and page numbers alternate.

All left-hand margins should be 1.5 inches to leave room for binding and page numbers of the main document should be on the right hand side. Every other page currently has a smaller left hand margin and the page numbers are on the left.

**Comment by dylanmikesell** [comment]
Fixed with commit 010a307.

Just need to remove two-side option from the \documentclass statement.
