### ISSUE TITLE
Page numbering roman numerals

### ISSUE THREAD

**Issue by RebekahFLee** [dylanmikesell/BSU_LaTeX_Thesis_Template#4]
The beginning of the document should be as follows:
Page i : Title page
Page ii: copyright page
page iii: Final reading approval page
all of the above pages should NOT have page numbers. Page iv is the Dedication page and should have the page number as well as all following pages (page number is in correct place at the bottom, centered)

**Comment by dylanmikesell** [comment]
Fixed with commit f587b37.
