### ISSUE TITLE
Separate title pages for appendices

### ISSUE THREAD

**Issue by RebekahFLee** [dylanmikesell/BSU_LaTeX_Thesis_Template#8]
One of the comments I got back was for a separate title page for appendices. I just used \newpage in my input files to fix it, but thought I should add it here for future reference.

The appendix should have a title page preceding the appendix content. This title page will contain the words “APPENDIX” and the corresponding letter according to the number of appendices. Below this Heading 1 title, a corresponding subheading (Heading 2) should indicate what is included in the appendix; this subheading should be a single clear title.

**Comment by dylanmikesell** [comment]
Fixed with commit b7b211d.
